import type { Metadata } from 'next';
import '../styles/globals.css';
import { robotoSans } from '@utils/fonts';
import RootProvider from './provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoSans.variable}  antialiased`}>
        <main className="font-roboto-sans">
          <RootProvider>{children}</RootProvider>
        </main>
      </body>
    </html>
  );
}
